export const MESSAGE = {
  /* Common Messages */
  UNAUTHORIZED: 'You are not authorized to access this resource.',
  USER_NOT_FOUND: 'User Not Found.',
  INVALID_TOKEN: 'Invalid Token.',
  USER_ALREADY_EXISTS: 'User Already Exists.',
  USER_NOT_VERIFIED: 'User Not Verified.',
  INVALID_CREDENTIALS: 'Invalid Credentials.',
  RESET_PASSWORD_TOKEN_SENT: 'Reset Password Token Sent.',
  USER_ALREADY_VERIFIED: 'User Already Verified.',
  USER_SIGNUP_SUCCESS: 'User Signup Successfully.',
  USER_LOGIN_SUCCESS: 'User Login Successfully.',
  USER_VERIFIED_SUCCESS: 'User Verified Successfully.',
  PASSWORD_RESET_SUCCESS: 'Password Reset Successfully.',
  REFRESH_TOKEN_SUCCESS: 'Refresh Token Successfully.',
  USER_UPDATE_SUCCESS: 'User Updated Successfully.',
  USER_FETCH_SUCCESS: 'User Fetched Successfully.',
  INSTRUCTOR_FETCH_SUCCESS: 'Instructor Fetched Successfully.',
  INVALID_INPUT: 'Invalid Input.',
  TOKEN_EXPIRED: 'Token Expired.',
  /* Content Messages */
  COURSE_ALREADY_EXISTS: 'Course Already Exists.',
  COURSE_NOT_FOUND: 'Course Not Found.',
  COURSE_CREATED_SUCCESS: 'Course Created Successfully.',
  COURSE_LIST_FETCHED_SUCCESS: 'Course List Fetched Successfully.',
  COURSE_DETAILS_FETCHED_SUCCESS: 'Course Details Fetched Successfully.',
  COURSE_UPDATED_SUCCESS: 'Course Updated Successfully.',
  COURSE_DELETED_SUCCESS: 'Course Deleted Successfully.',
  COURSE_ENROLLED_SUCCESS: 'Course Enrolled Successfully.',
  COURSE_ALREADY_ENROLLED: 'Course Already Enrolled.',
  COURSE_CREATION_FAILED: 'Course Creation Failed.',
  /* Review Messages */
  REVIEW_ALREADY_EXISTS: 'Review Already Exists.',
  REVIEW_NOT_FOUND: 'Review Not Found.',
  REVIEW_CREATED_SUCCESS: 'Review Created Successfully.',
  REVIEW_FETCHED_SUCCESS: 'Review Fetched Successfully.',
  REVIEW_UPDATED_SUCCESS: 'Review Updated Successfully.',
  REVIEW_DELETED_SUCCESS: 'Review Deleted Successfully.',
  REVIEW_REPLIED_SUCCESS: 'Review Replied Successfully.',
  /* Content Messages */
  CONTENT_ALREADY_EXISTS: 'Content Already Exists.',
  CONTENT_NOT_FOUND: 'Content Not Found.',
  CONTENT_CREATED_SUCCESS: 'Content Created Successfully.',
  CONTENT_UPDATED_SUCCESS: 'Content Updated Successfully.',
  CONTENT_DELETED_SUCCESS: 'Content Deleted Successfully.',
  /* Lecture Messages */
  LECTURE_ALREADY_EXISTS: 'Lecture Already Exists.',
  LECTURE_NOT_FOUND: 'Lecture Not Found.',
  LECTURE_CREATED_SUCCESS: 'Lecture Created Successfully.',
  LECTURE_UPDATED_SUCCESS: 'Lecture Updated Successfully.',
  LECTURE_DELETED_SUCCESS: 'Lecture Deleted Successfully.',
  /* Progress Messages */
  PROGRESS_UPDATED_SUCCESS: 'Progress Updated Successfully.',
  /* Order Messages */
  ORDER_NOT_FOUND: 'Order Not Found.',
  ORDER_CREATED_SUCCESS: 'Order Created Successfully.',
  ORDER_FETCHED_SUCCESS: 'Order Fetched Successfully.',
  COURSE_ALREADY_PURCHASED: 'Course Already Purchased.',
  /* Notification Messages */
  NOTIFICATION_FETCHED_SUCCESS: 'Notification Fetched Successfully.',
  NOTIFICATION_MARKED_AS_READ: 'Notification Marked As Read.',
};
