export const MESSAGE = {
  UNAUTHORIZED: 'You are not authorized to access this resource.',
  USER_NOT_FOUND: 'User Not Found.',
  INVALID_TOKEN: 'Invalid Token.',
  USER_ALREADY_EXISTS: 'User Already Exists.',
  USER_NOT_VERIFIED: 'User Not Verified.',
  INVALID_CREDENTIALS: 'Invalid Credentials.',
  RESET_PASSWORD_TOKEN_SENT: 'Reset Password Token Sent.',
  USER_ALREADY_VERIFIED: 'User Already Verified.',
  USER_SIGNUP_SUCCESS: 'User Signup Successfully.',
  USER_LOGIN_SUCCESS: 'User Login Successfully.',
  USER_VERIFIED_SUCCESS: 'User Verified Successfully.',
  PASSWORD_RESET_SUCCESS: 'Password Reset Successfully.',
  REFRESH_TOKEN_SUCCESS: 'Refresh Token Successfully.',
  USER_UPDATE_SUCCESS: 'User Updated Successfully.',
  COURSE_ALREADY_EXISTS: 'Course Already Exists.',
  COURSE_NOT_FOUND: 'Course Not Found.',
  COURSE_CREATED_SUCCESS: 'Course Created Successfully.',
  COURSE_LIST_FETCHED_SUCCESS: 'Course List Fetched Successfully.',
  COURSE_DETAILS_FETCHED_SUCCESS: 'Course Details Fetched Successfully.',
  COURSE_UPDATED_SUCCESS: 'Course Updated Successfully.',
  COURSE_DELETED_SUCCESS: 'Course Deleted Successfully.',
  COURSE_ENROLLED_SUCCESS: 'Course Enrolled Successfully.',
  COURSE_ALREADY_ENROLLED: 'Course Already Enrolled.',
  REVIEW_ALREADY_EXISTS: 'Review Already Exists.',
  REVIEW_NOT_FOUND: 'Review Not Found.',
  REVIEW_CREATED_SUCCESS: 'Review Created Successfully.',
  REVIEW_FETCHED_SUCCESS: 'Review Fetched Successfully.',
  REVIEW_UPDATED_SUCCESS: 'Review Updated Successfully.',
  REVIEW_DELETED_SUCCESS: 'Review Deleted Successfully.',
  REVIEW_REPLIED_SUCCESS: 'Review Replied Successfully.',
};
